apiVersion: apps/v1
kind: Deployment
metadata:
  name: integral-ecology-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: demo-site
          mountPath: /usr/share/nginx/html
      volumes:
      - name: demo-site
        configMap:
          name: demo-site-cm